// src/ui/button.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import { ReactNode } from 'react';

export interface Props {
  children?: ReactNode;
  onClick?: () => void;
  enabled?: boolean;
}

export const defaultProps: Props = {
  enabled: true,
};

export const style = (props: Props) => css`
  box-sizing: border-box;
  background: linear-gradient(0deg, #24282f 0, #2f343c 100%);
  border-radius: 5px;
  border: 1px solid #030c17;
  min-width: 30px;
  min-height: 30px;
  cursor: pointer;
  color: ${props.enabled ? '#bdbec0' : '#808080'};
  display: inline-block;

  &:hover {
    background: linear-gradient(180deg, #24282f 0, #2f343c 100%);
  }

  &:active {
    background: linear-gradient(180deg, #1a1d22 0, #2f343c 100%);
    color: ${props.enabled ? '#dbdcdf' : '#808080'};

    & > div {
      border: 1px solid #444;
      border-left-color: #555;
      border-right-color: #555;
      border-bottom-color: #999;
      top: 1px;
      left: 1px;
    }
  }

  & > div {
    text-shadow: 1px 1px 1px #080808;
    border-radius: 5px;
    position: absolute;
    width: 100%;
    height: 100%;
    border: 1px solid #999;
    border-left-color: #555;
    border-right-color: #555;
    border-bottom-color: #444;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 3px 10px;
    position: relative;
    user-select: none;

    & > * {
      margin-right: 5px;
    }

    & > *:last-child {
      margin-right: 0;
    }
  }
`;

export function Button(props: Props) {
  props = { ...defaultProps, ...props };
  return (
    <div css={style(props)} onClick={props.enabled ? props.onClick : undefined}>
      <div>{props.children}</div>
    </div>
  );
}

// src/gui/Button.svelte
<style lang="scss">
@import "theme";
.button {
  box-sizing: border-box;
  padding: 0;
  position: relative;
  user-select: none;
  border: 1px solid #030c17;
  border-radius: $border_radius_small;
  box-shadow: 2px 2px 4px 0px rgba(0, 0, 0, 0.25);

  .content {
    display: flex;
    align-items: center;
    justify-content: center;
    white-space: nowrap;
    padding: 5px;
  }
}

.isEnabled {
  @include linearGradient(#24282f, #2f343c);
  @include buttonBorder();
}

.isDown {
  @include linearGradient(#2f343c, #24282f);
  @include buttonBorder(true);
  box-shadow: inset 2px 2px 4px 0px rgba(0, 0, 0, 0.25);

  .content {
    position: relative;
    top: 1px;
    left: 1px;
  }
}

.round {
  border-radius: 10000px;

  &:before {
    border-radius: 10000px;
  }
}
</style>

<script lang="ts">
export let isEnabled: boolean = true;
export let isDown: boolean = false;
export let appearance: "box" | "round" = "box";
export let width: number | undefined = undefined;
export let height: number | undefined = undefined;
export let padding: number = 0;

let style = undefined;

const onMouseUp = () => {
  isDown = false;
  window.removeEventListener("mouseup", onMouseUp);
};

const onMouseDown = () => {
  isDown = true;
  window.addEventListener("mouseup", onMouseUp);
};

$: {
  let css = "";
  if (width) css += `width: ${width}px`;
  if (height) css += `height: ${height}px`;
  if (padding) css += `padding: ${padding}px`;
  style = css || undefined;
}
</script>

<button
  style="{style}"
  class="button {$$props.class}"
  class:isEnabled
  class:isDown
  class:round="{appearance === 'round'}"
  on:mousedown="{onMouseDown}"
  on:mousedown><div class="content"><slot /></div></button>
