// src/gui/Label.svelte
<style lang="scss">
@import "theme";

label {
  box-sizing: border-box;
  user-select: none;
  color: $color_label_enabled;
  text-shadow: 1px 1px 1px $color_label_shadow_enabled;
  font-size: 12px;
  white-space: nowrap;

  &.disabled {
    color: $color_label_disabled;
    text-shadow: 1px 1px 1px $color_label_shadow_disabled;
  }

  &.link {
    color: $color_label_link;
    text-decoration: underline;
    cursor: pointer;
  }
}
</style>

<script lang="ts">
export let enabled: boolean = true;
export let text: string = "";
export let url: string = "";
</script>

<!-- svelte-ignore a11y-label-has-associated-control -->
<label class="label" class:disabled="{!enabled}" class:link="{url.length > 0}">
  {text}
</label>

// src/ui/label.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import { ReactNode } from 'react';
import Color from 'color';

export interface Props {
  text: string;
  enabled?: boolean;
  link?: boolean;
  onClick?: () => void;
}

export const defaultProps: Props = {
  text: 'Label',
  enabled: true,
  link: false,
};

export const style = (props: Props) => {
  const { enabled, link, onClick } = props;
  const shadowColor = enabled ? '#080808' : '#383838';
  const textColor = Color(link ? '#57b1ff' : '#bdbec0');
  const isInteractive = !!(link || onClick) && enabled;
  return css`
    box-sizing: border-box;
    user-select: none;
    text-shadow: 1px 1px 1px ${shadowColor};
    color: ${enabled ? textColor.hex() : textColor.darken(0.5).hex()};
    text-decoration: ${link ? 'underline' : 'normal'};
    cursor: ${isInteractive ? 'pointer' : 'default'};
    &:active {
      ${isInteractive ? 'color:' + textColor.lighten(0.2).hex() : ''};
    }
  `;
};

export function Label(props: Props) {
  props = { ...defaultProps, ...props };
  return (
    <label
      css={style(props)}
      onClick={props.enabled ? props.onClick : undefined}
    >
      {props.text}
    </label>
  );
}
