// src/gui/PushButton.svelte
<style lang="scss">
@import "theme";
:global(.pushbutton .content > *) {
  margin-right: $spacing_small;
}
:global(.pushbutton .content > *:last-child) {
  margin-right: 0;
}
</style>

<script lang="ts">
import Button from "./Button.svelte";
import Label from "./Label.svelte";
import Icon from "./Icon.svelte";

export let label: string | undefined = undefined;
export let iconSrc: string | undefined = undefined;
export let iconName: string | undefined = undefined;
export let iconWidth: number | undefined = 16;
export let iconHeight: number | undefined = undefined;
</script>

<Button on:mousedown class="pushbutton" isEnabled="{$$props.isEnabled}">
  {#if label}
    <Label text="{label}" />
  {/if}
  {#if iconSrc || iconName}
    <Icon
      src="{iconSrc}"
      name="{iconName}"
      width="{iconWidth}"
      height="{iconHeight}" />
  {/if}
</Button>

// src/ui/pushButton.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import { Label } from './label';
import { Icon } from './icon';
import { AbstractButton, Props as AbstractButtonProps } from './abstractButton';

export type Props = {
  label?: string;
  icon?: string;
  iconWidth?: number;
  iconBorder?: boolean;
} & Pick<AbstractButtonProps, 'enabled' | 'toggle' | 'onClick' | 'onToggled'>;

export const defaultProps: Props = {
  enabled: true,
};

export const style = () => {
  return css`
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;

    & > * {
      margin: 5px 5px;
    }

    & > *:first-child {
      margin-left: 10px;
    }

    & > *:last-child {
      margin-right: 10px;
    }
  `;
};

export function PushButton(props: Props) {
  const {
    label,
    icon,
    iconWidth,
    iconBorder,
    enabled,
    toggle,
    onClick,
    onToggled,
  } = {
    ...defaultProps,
    ...props,
  };

  const abstractButtonProps: Partial<AbstractButtonProps> = {
    enabled,
    toggle,
    onClick,
    onToggled,
  };

  return (
    <AbstractButton {...abstractButtonProps}>
      <div css={style()} className="pushbutton">
        {icon !== undefined ? (
          <Icon src={icon} width={iconWidth} border={iconBorder} />
        ) : null}
        {label !== undefined ? <Label text={label} enabled={enabled} /> : null}
      </div>
    </AbstractButton>
  );
}
