// src/gui/components/Panel.svelte
<script lang="ts" context="module">
export const staticVar = 500;
</script>

<script lang="ts">
import { MenuBarItem } from '../menu';

import Label from './Label.svelte';
import MenuBar from './MenuBar.svelte';

export let title: string | undefined = undefined;
export let menuBar: MenuBarItem[] | undefined = undefined;
</script>

<div class="panel" class:withTitle="{!!title}" data-component="panel">
  {#if title}
    <div class="panel-title"><Label text="{title}" /></div>
  {/if}
  {#if menuBar}
    <MenuBar items="{menuBar}" />
  {/if}
  <div class="panel-content"><slot /></div>
</div>

<style lang="scss">
@import '../theme';
.panel {
  box-sizing: border-box;
  /* border-top: 1px solid #686868;
  border-left: 1px solid #484848;
  border-right: 1px solid #484848;
  border-bottom: 1px solid #333333; */
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  height: 100%;
  width: 100%;

  &.withTitle {
    border-radius: $border_radius_small;
  }

  .panel-title {
    @include linear_gradient(#3b4046, #2c3038);
    box-sizing: border-box;
    padding: $spacing_small;
    /* border-radius: $border_radius_small;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0; */
  }

  .panel-content {
    box-sizing: border-box;
    /* padding: $spacing_tiny; */
    border-radius: $border_radius_small;
    flex-grow: 1;
  }
}
</style>

// src/ui/components/panel.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import { ReactNode } from 'react';
import { Label } from './label';
import { MenuBar, MenuBarItem } from './menuBar';
import { borderRadius, boxBorder, panelBorder, reset } from './theme';
import { init } from '../util';

export interface Props {
  children?: ReactNode;
  width?: number;
  height?: number;
  title?: string;
  menu?: MenuBarItem[];
}

export const defaultProps: Props = {};

export const style = ({ width, height }: Props) => css`
  ${borderRadius}
  ${reset}
  display: flex;
  flex-direction: column;
  position: relative;
  width: ${width ? `${width}px` : '100%'};
  height: ${height ? `${height}px` : '100%'};
  background: linear-gradient(0deg, #515254 0, #49494c 100%);
  padding: 5px;

  .panel-title {
    background: linear-gradient(0deg, #47515a 0, #2c2f34 100%);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 5px;
    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
    ${panelBorder}
  }

  .panel-inner {
    ${boxBorder}
    ${borderRadius}
    flex-grow: 1;
    width: 100%;
    height: 100%;
    padding: 5px;
    min-height: 20px;
  }
`;

export function Panel(props: Props) {
  const [{ children, title, menu }, css] = init(props, defaultProps, style);

  return (
    <div css={css} className="panel">
      {title ? (
        <div className="panel-title">
          <Label text={title} />
        </div>
      ) : null}
      {menu ? <MenuBar items={menu}></MenuBar> : null}
      <div className="panel-inner">{children}</div>
    </div>
  );
}
