// src/ui/layout/section.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react';
import { ReactNode } from 'react';
import { reset } from '../components/theme';
import { init } from '../util';

export interface Props {
  children: ReactNode;
  title: string;
}

export const defaultProps: Props = {
  children: null,
  title: 'Untitled',
};

export const style = ({}: Props) => {
  return css`
    ${reset}

    padding: 5px 10px;
    display: flex;
    border-radius: 5px;
    border: 1px inset #7f7f7f8a;
    background-color: rgba(0, 0, 0, 0.05);
    margin-bottom: 5px;
    padding-bottom: 10px !important;

    > * {
      margin-right: 5px;
    }

    > *:last-child {
      margin-right: 0;
    }

    legend {
      color: #bcbcbc;
      padding: 2px 5px;
      border-radius: 5px;
      border-bottom: 1px solid #090e0e;
      border-top: 1px solid #9c9c9c;
      background-color: #41484e;
      font-size: 11px;
      text-shadow: 1px 1px 1px #080808;
    }
  `;
};

export function Section(props: Props) {
  const [{ children, title }, css] = init(props, defaultProps, style);
  return (
    <fieldset css={css} className="section">
      <legend>{title}</legend>
      {children}
    </fieldset>
  );
}

// src/examples/Section.svelte
<style lang="scss">
@import "../gui/theme";

.section {
  box-sizing: border-box;
  user-select: none;
  padding: 0 ($spacing_small * 2);
  border-radius: $spacing_small;
  border: 1px inset #7f7f7f8a;
  background-color: rgba(0, 0, 0, 0.05);
  margin-bottom: ($spacing_small * 2);
  padding-bottom: 8px;
  padding-top: 10px;

  legend {
    position: relative;
    left: $spacing_small * -1;
    top: -2px;
    color: #a8e9f3;
    padding: 2px $spacing_small;
    border-radius: $spacing_small;
    border-bottom: 1px solid #666666;
    border-top: 1px solid #9c9c9c;
    background-color: #545454;
    font-size: 11px;
    text-shadow: -1px -1px 1px #080808;
    padding-bottom: 3px;
  }

  div {
    display: flex;
  }

  div.horizontal {
    flex-direction: row;

    :global(&.content > *) {
      margin-right: $spacing_small;
    }

    :global(&.content > *:last-child) {
      margin-right: 0;
    }
  }

  div.vertical {
    flex-direction: column;

    :global(&.content > *) {
      margin-bottom: $spacing_small;
    }

    :global(&.content > *:last-child) {
      margin-bottom: 0;
    }
  }
}
</style>

<script lang="ts">
import type { Direction } from "../gui/types";
export let title: string = "";
export let direction: Direction = "horizontal";
</script>

<fieldset class="section">
  <legend>{title}</legend>
  <div
    class="content"
    class:horizontal="{direction === 'horizontal'}"
    class:vertical="{direction === 'vertical'}">
    <slot />
  </div>
</fieldset>
